export const SAVEDNEWS_LIST_REQUEST = "SAVEDNEWS_LIST_REQUEST";
export const SAVEDNEWS_LIST_SUCCESS = "SAVEDNEWS_LIST_SUCCESS";
export const SAVEDNEWS_LIST_FAIL  = "SAVEDNEWS_LIST_FAIL";

//for saving
export const SAVE_NEWS_REQUEST = "SAVE_NEWS_REQUEST";
export const SAVE_NEWS_SUCCESS = "SAVE_NEWS_SUCCESS";
export const SAVE_NEWS_FAIL  = "SAVE_NEWS_FAIL";
